directories:
  output: electron-dist
  buildResources: build
appId: com.kinsfolkrepublic.tradingjournaldesktop
productName: Kinsfolk Republic Trading Journal
files:
  - filter:
      - dist/**/*
      - main.js
      - preload.js
      - package.json
      - public/krtj-icon.ico
compression: maximum
win:
  target: nsis
  icon: public/krtj-icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  installerIcon: public/krtj-icon.ico
  uninstallerIcon: public/krtj-icon.ico
  artifactName: KRTJ-Desktop-Setup-${version}.exe
  differentialPackage: true
publish:
  provider: generic
  url: https://kinsfolk-republic-trading-journal-v.vercel.app/downloads/
electronVersion: 27.3.11
